Refactor expr2ct::convert_with_precedence to avoid MSVC limitation
Visual Studio fails with "fatal error C1061: compiler limit: blocks
nested too deeply" when attempting to add an additional expression to be
handled. To avoid this, factor out the trivial cases invoking
convert_function into a separate method.